Change to correct rubocop version
We were seeing the following error, which relates to rubocop
specifying the wrong Ruby version.

Error: RuboCop found unsupported Ruby version 2.2 in `TargetRubyVerion` parameter (in .rubocop.yml). 2.2-compatible analysis was dropped after version 0.69.
Supported versions: 2.3, 2.4, 2.5, 2.6, 2.7