Pin connection_pool to < 3
We can't support connection_pool 3 because it relies on a version of
sidekiq we don't support. This was causing an error where the assets
could not compile before deployment. We are pinning the version to
a working one to ensure it does not fail again.

Error from deployment:
rails assets:precompile
...
 bin/rails aborted!
 ArgumentError: wrong number of arguments (given 1, expected 0) (ArgumentError)
 /app/config/environment.rb:5:in `<main>'